/*
 * This file is generated by jOOQ.
 */
package com.example.sample.entity;


import com.example.sample.entity.tables.Product;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;
}
